const app = document.querySelector('#app');
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today = () => new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Taipei'}).format(new Date());
const duration = n => `${Math.floor(n/60)} 小時 ${n%60} 分`;
const time = v => v ? v.slice(11,16) : '--:--';
let token = sessionStorage.getItem('flyerToken') || '', data, selectedDate = today(), busy = false;
function notice(s){const el=document.querySelector('#message');el.textContent=s;el.classList.add('visible');clearTimeout(notice.timer);notice.timer=setTimeout(()=>el.classList.remove('visible'),5000);}
async function api(action,payload={}){if(!window.API_URL)throw Error('請先在 config.js 設定 Apps Script API 網址。');const res=await fetch(window.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token,...payload}),redirect:'follow'});const result=await res.json();if(!result.ok)throw Error(result.error);return result.data;}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){notice(e.message);}finally{busy=false;document.querySelector('#logout').disabled=false;if(data)render();else login();}}
function login(){document.querySelector('#logout').hidden=true;app.innerHTML=`<section class="card login"><h2>開始今天的工作</h2><p class="muted">輸入姓名與個人 PIN，查看你的排班與紀錄。</p>${!window.API_URL?'<p class="hint">尚未連接 Google 服務。請依 README 完成部署，再設定 config.js。</p>':''}<form id="login"><label>姓名<input name="name" required autocomplete="username" maxlength="50"></label><label>個人 PIN<input name="pin" type="password" required autocomplete="current-password"></label><button class="full">登入</button></form></section>`;document.querySelector('#login').onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));run(async()=>{const r=await api('login',values);token=r.token;sessionStorage.setItem('flyerToken',token);await refresh();});};}
async function refresh(){data=await api('dashboard',{date:selectedDate});render();}
function imageLinks(r){return data.images.filter(i=>i.record_id===r.record_id).map((i,n)=>`<a href="${escapeHtml(i.drive_url)}" target="_blank" rel="noopener">路線圖 ${n+1} ↗</a>`).join('');}
function status(r){return r.actual_end?'已下班':r.actual_start?'工作中':'尚未上班';}
function recordCard(r,admin=false){return `<div class="record"><div class="row"><strong>${escapeHtml(admin?r.name:r.date)}</strong><span class="badge ${r.actual_start&&!r.actual_end?'working':''}">${status(r)}</span></div><p>預計 ${escapeHtml(r.planned_start||'未設定')} · 實際 ${time(r.actual_start)}～${time(r.actual_end)}</p><p>今日 ${duration(r.minutes)}${admin?` · 本週 ${duration(data.weekly[r.worker_id]||0)}`:''}</p><div class="links">${imageLinks(r)||'<span class="muted">尚未上傳路線圖</span>'}</div>${r.note?`<p>${escapeHtml(r.note)}</p>`:''}${admin?`<button class="secondary" data-history="${escapeHtml(r.worker_id)}">查看個人歷史</button><details><summary>時間修改歷程</summary>${data.audit.filter(a=>a.record_id===r.record_id).map(a=>`<p class="muted">${escapeHtml(a.changed_at)} · ${escapeHtml(a.field)}<br>${escapeHtml(a.old_value||'空白')} → ${escapeHtml(a.new_value)}（${escapeHtml(a.kind)}）</p>`).join('')||'<p class="muted">尚無修改</p>'}</details>`:''}</div>`;}
function render(){document.querySelector('#logout').hidden=false;const admin=data.user.role==='admin';app.innerHTML=`<section class="card intro"><small style="color:#c7ded3">${admin?'管理者工作台':'今天，也一步一步完成'}</small><h2 style="margin-top:10px">${escapeHtml(data.user.name)}</h2><div class="row"><span>${escapeHtml(selectedDate)} · ${admin?'人員出勤總覽':'我的工作紀錄'}</span><button class="secondary" id="refresh">重新整理</button></div></section>${admin?adminView():workerView()}<section class="card"><details><summary>修改我的 PIN</summary><form id="change-pin"><label>目前 PIN<input name="old_pin" type="password" autocomplete="current-password" required></label><label>新 PIN<input name="new_pin" type="password" autocomplete="new-password" minlength="6" maxlength="100" required></label><button>更新 PIN</button></form></details></section>`;document.querySelector('#refresh').onclick=()=>run(refresh);document.querySelector('#change-pin').onsubmit=e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));run(async()=>{await api('changePin',p);notice('PIN 已更新');});};bind(admin);}
function workerView(){const r=data.records.find(r=>r.date===selectedDate);return `<div class="columns"><section class="card"><h2>今日工作</h2>${!r?'<p class="muted">今天未排班，請聯絡管理者。</p>':`<label>預計上班</label><div class="value">${escapeHtml(r.planned_start||'未設定')}</div><div class="grid">${['start','end'].map(k=>`<div><div class="row"><label>實際${k==='start'?'上':'下'}班</label><button class="edit" data-edit="${k}" data-record="${r.record_id}">編輯</button></div><div class="value">${time(r['actual_'+k])}</div><button class="full" data-clock="${k}" data-record="${r.record_id}" ${r['actual_'+k]||(k==='end'&&!r.actual_start)?'disabled':''}>${r['actual_'+k]?'已'+(k==='start'?'上':'下')+'班':(k==='start'?'上':'下')+'班'}</button></div>`).join('')}</div><div class="grid stats"><div><label>今日工時</label><p class="stat">${duration(r.minutes)}</p>${r.actual_start&&!r.actual_end?'<small>工作中 · 下班後結算</small>':''}</div><div><label>本週工時</label><p class="stat">${duration(data.weekly[data.user.worker_id]||0)}</p><small>週一至週日</small></div></div><h3>今日路線圖 · ${data.images.filter(i=>i.record_id===r.record_id).length} 張</h3><div class="links">${imageLinks(r)}</div><label class="button secondary full" style="text-align:center">＋ 上傳路線截圖<input id="upload" type="file" accept="image/jpeg,image/png,image/webp" multiple hidden></label><p class="muted">每張最多 5 MB，可一次選多張。</p><form id="note"><label>備註<textarea name="note" maxlength="2000">${escapeHtml(r.note)}</textarea></label><button class="secondary">儲存備註</button></form>`}</section><section class="card"><h2>我的紀錄</h2><p class="muted">最近 30 天 · 本週 ${duration(data.weekly[data.user.worker_id]||0)}</p>${recentDays(data.records)}</section></div>`;}
function recentDays(records){return Array.from({length:30},(_,n)=>{const d=new Date(selectedDate+'T12:00:00+08:00');d.setDate(d.getDate()-n);const date=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Taipei'}).format(d);const r=records.find(r=>r.date===date);return r?recordCard(r):`<div class="record row"><span>${date}</span><span class="muted">未排班</span></div>`;}).join('');}
function adminView(){const workers=data.workers.filter(w=>w.role!=='admin');return `<section class="card"><label>查看日期<input id="date" type="date" value="${selectedDate}"></label>${data.records.filter(r=>r.date===selectedDate).map(r=>recordCard(r,true)).join('')||'<p class="muted">這天尚未排班。</p>'}</section><section class="card"><h2>設定預計上班</h2>${workers.length?'':'<p class="hint">請先在下方新增工讀生，再設定排班。</p>'}<form id="schedule"><div class="grid"><label>日期<input type="date" name="date" value="${selectedDate}" required></label><label>工讀生<select name="worker_id" required>${workers.map(w=>`<option value="${escapeHtml(w.worker_id)}">${escapeHtml(w.name)}</option>`).join('')}</select></label></div><label>預計上班時間<input type="time" name="planned_start" required></label><button ${workers.length?'':'disabled'}>儲存排班</button></form></section><section class="card"><h2>新增工讀生</h2><form id="create-worker"><label>姓名<input name="name" required maxlength="50" autocomplete="off"></label><label>個人 PIN<input name="pin" type="password" required minlength="6" maxlength="100" autocomplete="new-password"></label><button>建立帳號</button></form></section><section id="history" class="card" hidden></section>`;}
function bind(admin){if(admin){document.querySelector('#create-worker').onsubmit=e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));run(async()=>{await api('createWorker',p);await refresh();notice('工讀生帳號已建立');});};document.querySelector('#date').onchange=e=>{selectedDate=e.target.value;run(refresh);};document.querySelector('#schedule').onsubmit=e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));run(async()=>{await api('schedule',p);await refresh();notice('排班已儲存');});};document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>{const el=document.querySelector('#history');el.hidden=false;el.innerHTML=`<h2>個人歷史紀錄</h2>${data.records.filter(r=>r.worker_id===b.dataset.history).sort((a,b)=>b.date.localeCompare(a.date)).map(r=>recordCard(r)).join('')}`;el.scrollIntoView({behavior:'smooth'});});return;}
document.querySelectorAll('[data-clock]').forEach(b=>b.onclick=()=>run(async()=>{await api('clock',{record_id:b.dataset.record,field:b.dataset.clock});await refresh();}));
document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const r=data.records.find(r=>r.record_id===b.dataset.record),field=b.dataset.edit;const v=prompt('輸入實際日期時間（YYYY-MM-DDTHH:mm），跨午夜請填下一天日期。',r['actual_'+field]?.slice(0,16)||`${r.date}T18:30`);if(v===null)return;run(async()=>{await api('edit',{record_id:r.record_id,field,value:v});await refresh();notice('時間已更新，工時已重新計算');});});
const r=data.records.find(r=>r.date===selectedDate);const note=document.querySelector('#note');if(note)note.onsubmit=e=>{e.preventDefault();const value=e.target.elements.note.value;run(async()=>{await api('note',{record_id:r.record_id,note:value});await refresh();notice('備註已儲存');});};const upload=document.querySelector('#upload');if(upload)upload.onchange=e=>{const files=[...e.target.files];run(async()=>{for(const f of files){if(f.size>5*1024*1024)throw Error('每張圖片最多 5 MB');if(!['image/jpeg','image/png','image/webp'].includes(f.type))throw Error('請選擇 JPG、PNG 或 WebP 圖片');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(f);});await api('upload',{record_id:r.record_id,mime:f.type,base64});}await refresh();notice('路線圖已上傳');});};}
document.querySelector('#logout').onclick=()=>{token='';data=null;sessionStorage.removeItem('flyerToken');login();};
if(token)run(refresh);else login();
